version: '3'

services:
  pg:
    image: postgres
    ports:
      - ${SM_API_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${SM_API_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SM_API_POSTGRES_PASS}
      POSTGRES_DB: ${SM_API_POSTGRES_DB}
    restart: always
    networks:
      - net_rxpm

  redis:
    image: redis:alpine
    ports:
      - ${SM_API_REDIS_PORT}:6379
    command: redis-server
    restart: always
    networks:
      - net_rxpm

  adminer:
    image: adminer
    ports:
      - 8989:8080
    restart: always
    networks:
      - net_rxpm

networks:
  net_rxpm:
